default_language_version:
    python: python3.9
exclude: "^venv$"
repos:
    - repo: "https://github.com/pre-commit/pre-commit-hooks"
      rev: v4.4.0
      hooks:
          - id: check-toml
          - id: check-yaml
    - repo: "https://github.com/psf/black"
      rev: 23.1.0
      hooks:
          - id: black-jupyter
